// Auth constants
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_PROFILE_REQUEST = 'AUTH_PROFILE_REQUEST';
export const AUTH_PROFILE_SUCCESS = 'AUTH_PROFILE_SUCCESS';
export const AUTH_PROFILE_FAIL = 'AUTH_PROFILE_FAIL';

// Game constants
export const GAMES_LIST_REQUEST = 'GAMES_LIST_REQUEST';
export const GAMES_LIST_SUCCESS = 'GAMES_LIST_SUCCESS';
export const GAMES_LIST_FAIL = 'GAMES_LIST_FAIL';

export const GAME_DETAIL_REQUEST = 'GAME_DETAIL_REQUEST';
export const GAME_DETAIL_SUCCESS = 'GAME_DETAIL_SUCCESS';
export const GAME_DETAIL_FAIL = 'GAME_DETAIL_FAIL';

export const GAME_CREATE_REQUEST = 'GAME_CREATE_REQUEST';
export const GAME_CREATE_SUCCESS = 'GAME_CREATE_SUCCESS';
export const GAME_CREATE_FAIL = 'GAME_CREATE_FAIL';

export const GAME_UPDATE_REQUEST = 'GAME_UPDATE_REQUEST';
export const GAME_UPDATE_SUCCESS = 'GAME_UPDATE_SUCCESS';
export const GAME_UPDATE_FAIL = 'GAME_UPDATE_FAIL';
export const GAME_UPDATE_RESET = 'GAME_UPDATE_RESET';
export const GAME_CREATE_RESET = 'GAME_CREATE_RESET';

export const GAME_DELETE_REQUEST = 'GAME_DELETE_REQUEST';
export const GAME_DELETE_SUCCESS = 'GAME_DELETE_SUCCESS';
export const GAME_DELETE_FAIL = 'GAME_DELETE_FAIL';

// Cart constants
export const CART_LOAD_REQUEST = 'CART_LOAD_REQUEST';
export const CART_LOAD_SUCCESS = 'CART_LOAD_SUCCESS';
export const CART_LOAD_FAIL = 'CART_LOAD_FAIL';

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_CLEAR = 'CART_CLEAR';

// Review constants
export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';

// Order constants
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

// Wishlist constants
export const WISHLIST_TOGGLE_SUCCESS = 'WISHLIST_TOGGLE_SUCCESS';
